if("object"==typeof JSON)var json_encode=JSON.stringify;else"function"!=typeof json_encode&&(json_encode=null,function(){function a(a){return'"'+a.replace(/\n/g,"\\n").replace(/(['"\\])/g,"\\$1")+'"'}function b(n,k){var c,g,f,p,h=e,m,d=k[n];d&&"object"===typeof d&&"function"===typeof d.toJSON&&(d=d.toJSON(n));"function"===typeof j&&(d=j.call(k,n,d));switch(typeof d){case "string":return a(d);case "number":return isFinite(d)?""+d:"null";case "boolean":case "null":return""+d;case "object":if(!d)return"null";
e+=l;m=[];if("[object Array]"===Object.prototype.toString.apply(d)){p=d.length;for(c=0;c<p;c+=1)m[c]=b(c,d)||"null";f=0===m.length?"[]":e?"[\n"+e+m.join(",\n"+e)+"\n"+h+"]":"["+m.join(",")+"]";e=h;return f}if(j&&"object"===typeof j)for(p=j.length,c=0;c<p;c+=1)g=j[c],"string"===typeof g&&(f=b(g,d))&&m.push(a(g)+(e?": ":":")+f);else for(g in d)Object.hasOwnProperty.call(d,g)&&(f=b(g,d))&&m.push(a(g)+(e?": ":":")+f);f=0===m.length?"{}":e?"{\n"+e+m.join(",\n"+e)+"\n"+h+"}":"{"+m.join(",")+"}";e=h;return f}}
json_encode=function(a,k,c){var g;l=e="";if("number"===typeof c)for(g=0;g<c;g+=1)l+=" ";else"string"===typeof c&&(l=c);if((j=k)&&"function"!==typeof k&&("object"!==typeof k||"number"!==typeof k.length))throw Error("json_encode");return b("",{"":a})}}());
function sppc_agent(){var a=((navigator||{}).userAgent||"").toLowerCase(),b={safari:/safari/.test(a)&&!/chrome/.test(a),msie:/msie/.test(a)&&!/opera/.test(a),webkit:/webkit/.test(a),firefox:/firefox/.test(a),chrome:/chrome/.test(a),opera:/opera/.test(a)};b.version=b.safari?a.match(/version\/([\d.]+)/):a.match(/.+(?:ox|me|ra|ie|rv)[\/: ]+([\d.]+)/);b.version=parseInt((b.version||[])[1]);return b}
function sppc_flash(){var a=0;if(navigator.plugins&&navigator.plugins.length){if(navigator.plugins["Shockwave Flash"]||navigator.plugins["Shockwave Flash 2.0"])a=1}else if(navigator.mimeTypes&&navigator.mimeTypes.length)(x=navigator.mimeTypes["application/x-shockwave-flash"])&&x.enabledPlugin&&(a=1);else if(navigator.userAgent&&0<=navigator.userAgent.indexOf("MSIE")&&-1!=navigator.appVersion.indexOf("Win"))try{for(i=3;12>=i;i++)if(eval('new ActiveXObject("ShockwaveFlash.ShockwaveFlash.'+i+'")')){a=
1;break}}catch(b){}else a=-1;return a}
function sppc_defaults(a){"object"!=typeof a&&(a={});"object"!=typeof a.vars&&(a.vars={});"undefined"==typeof a.vars.site_id&&(a.vars.site_id=a.site);"undefined"==typeof a.vars.channel_id&&(a.vars.channel_id=a.channel);"undefined"==typeof a.palette&&(a.palette="1");"undefined"==typeof a.cookie&&(a.cookie=Math.round(1E3*Math.random()));"undefined"==typeof a.use_flash&&(a.use_flash=sppc_flash());"undefined"==typeof a.keywords&&(a.keywords=[]);"undefined"==typeof a.refresh&&(a.refresh="0");"undefined"==
typeof a.refresh_int&&(a.refresh_int="200");return a}
function sppc_get_url(a){var b=function(a,b){"function"==typeof b&&(b=b());return!b||b instanceof Array&&!(0<b.length)?"":"&"+a+"="+escape("object"==typeof b?json_encode(b):b)};return"http://delivery.trafficforce.com/show_std.php?ident="+Math.round(1E4*Math.random())+b("id_site",a.site)+b("id_channel",a.channel)+b("ref",document.URL)+b("sr",document.referrer)+b("id_dimension",a.dimension)+b("width",a.width)+b("height",a.height)+b("id_palette",a.palette)+b("id_user",a.user)+b("ck",a.cookie)+b("uf",
a.use_flash)+b("t_link",a.t_link)+b("m1",a.misc1)+b("m2",a.misc2)+b("m3",a.misc3)+b("vars",a.vars)+b("k",a.keywords)}function sppc_get_closest_link(a){for(;"object"==typeof a&&null!=a;){if("string"==typeof a.tagName&&"a"==a.tagName.toLowerCase())return a;a=a.parentNode}return!1}
function sppc_pu(a){a=sppc_defaults(a);var b=sppc_agent(),n=function(a,b,c,g){var d=new Date;d.setDate(d.getDate()+c);b=escape(b)+";path=/"+(null==c?"":"; expires="+d.toUTCString())+(null==g?"":"; domain="+g);document.cookie=a+"="+b},k=a.domain||null,c=function(b){n("pu_count",1,null,k);document.removeEventListener("click",c,!1);var g=sppc_get_closest_link(b.target),h=g&&!g.href.match(/#/)?g.href:document.location.href;window.open(h).focus();window.location.href=sppc_get_url(a);g&&b.preventDefault()},
g=function(f){n("pu_count",1,null,k);document.removeEventListener("click",g,!1);sppc_get_closest_link(f.target);if((b.msie&&9<=b.version||b.chrome||b.firefox&&4<=b.version)&&1!=f.button&&2==f.button)return!1;var c=a.width||1100;f=a.height||800;var h=window.screenTop||window.screenY,m=window.screenLeft||window.screenX,d=0,q=0;"number"==typeof window.innerWidth?(d=window.innerWidth,q=window.innerHeight):document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?
(d=document.documentElement.clientWidth,q=document.documentElement.clientHeight):document.body&&(document.body.clientWidth||document.body.clientHeight)&&(d=document.body.clientWidth,q=document.body.clientHeight);f="width="+c+", height="+f+", scrollbars=yes,resizable=yes,toolbar=no, menubar=no,status=no,location=no,left="+(m+d/2-c/2)+",top="+(h+q/2-f/2);c=sppc_get_url(a);if(b.chrome&&23<b.version)h=document.createElement("a"),f=document.createEvent("MouseEvents"),h.target="_blank",h.href=c,f.initMouseEvent("click",
!0,!0,window,0,0,0,0,0,!0,!1,!1,!0,0,null),h.dispatchEvent(f);else if(b.firefox&&3.6<b.version||b.chrome)c=window.open(c,"pornpu",f),f=window.open("about:blank"),f.focus(),f.close(),c.blur(),window.focus();else{if(c=window.open(c,"pornpu",f))c.blur(),c.opener.window.focus(),window.self.window.focus(),window.focus();b.webkit&&(h=top.window.document.createElement("a"),h.href="data:text/html,<script>window.close();\x3c/script>",document.getElementsByTagName("body")[0].appendChild(h),f=top.window.document.createEvent("MouseEvents"),
f.initMouseEvent("click",!1,!0,window,0,0,0,0,0,!0,!1,!1,!0,0,null),h.dispatchEvent(f),h.parentNode.removeChild(h))}};0<parseInt(function(a){return(a=document.cookie.match("(^|;) ?"+a+"=([^;]*)(;|$)"))?unescape(a[2]):null}("pu_count"))||document.addEventListener("click","string"==typeof a.type&&"mobile"==a.type?c:g)}
function sppc_show(a){function b(){if(-1==a.refresh||a.refresh--){var c=document.getElementById(k);c.src=c.src;setTimeout(b,1E3*a.refresh_int)}}a=sppc_defaults(a);"undefined"==typeof a.t_link&&(a.t_link="",a.t_regex=/[\?&]t_link=([^&#]*)/,null!=(results=a.t_regex.exec(window.location.href))&&(a.t_link="&t_link="+results[1]));var n=sppc_get_url(a),k=Math.round(1E6*Math.random()),c=unescape("%3Ciframe src='"+escape(n)+"' rel='nofollow' id='"+k+"' scrolling='no' allowtransparency='true' style='background-color:transparent' frameborder='0' width='"+
a.width+"' height='"+a.height+"'%3E%3C/iframe%3E");"function"==typeof a.display?a.display(c,{url:n,width:a.width,height:a.height,id:k}):"complete"!=document.readyState&&document.write(c);a.refresh&&setTimeout(b,1E3*a.refresh_int)};
